# Generated by Django 5.2.7 on 2026-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_drugsearchhistory_pharmacyselectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='Cameroon', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(default='Centre', max_length=50),
        ),
    ]
